[0m13:23:45.986016 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027A414DFED0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027A3F36D510>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027A4155C090>]}


============================== 13:23:45.989023 | d3e682e8-f63f-4318-bc69-789056b26eca ==============================
[0m13:23:45.989023 [info ] [MainThread]: Running with dbt=1.5.0
[0m13:23:45.990023 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\Lenin\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m13:23:45.991023 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Lenin\Documents\Development\TextQL\projects\dbt-doc-py\dbt_doc_py\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:23:45.991023 [debug] [MainThread]: Command `dbt docs generate` failed at 13:23:45.991023 after 0.02 seconds
[0m13:23:45.992025 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027A4155C190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027A411B4B50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027A411B6AD0>]}
[0m13:23:45.992025 [debug] [MainThread]: Flushing usage events
[0m18:16:20.636419 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AF5420B110>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AF541566D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AF5450CE10>]}


============================== 18:16:20.639956 | 06260c2a-7910-4ff0-b566-654a8f6c955a ==============================
[0m18:16:20.639956 [info ] [MainThread]: Running with dbt=1.5.0
[0m18:16:20.640955 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Lenin\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m18:16:20.641947 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Lenin\Documents\Development\TextQL\projects\dbt-doc-py\dbt_doc_py\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m18:16:20.641947 [debug] [MainThread]: Command `dbt docs generate` failed at 18:16:20.641947 after 0.08 seconds
[0m18:16:20.642948 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AF541392D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AF5431E910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AF54157C10>]}
[0m18:16:20.642948 [debug] [MainThread]: Flushing usage events
